"$schema" = 'https://starship.rs/config-schema.json'

scan_timeout = 10
add_newline = false

format = '''
$character$status([](bg:236 fg:16)${env_var.PS1_EXTRA}[](inverted bg:236 fg:16))([](bg:236 fg:16)$git_branch$git_metrics[](inverted bg:236 fg:16))([](bg:236 fg:16)${env_var.NIX_SHELL_NAME}[](inverted bg:236 fg:16)) $username[@](0)$hostname[:](0)$directory$fill$cmd_duration$time [](241)
 [\$ ](bold blue)
'''

[character]
format = "$symbol"
success_symbol = "[](fg:241 bg:16)"
error_symbol = ""

[status]
format = "[$status]($style)[]($style inverted)"
success_style = "bg:241 fg:16"
failure_style = "bg:red fg:16"
disabled = false

[env_var.PS1_EXTRA]
format = "[$env_value]($style)"
style = "bg:236"

[env_var.NIX_SHELL_NAME]
format = "[󱄅 ](bg:236 fg:4)[$env_value]($style)"
style = "bg:236 fg:249"


[git_branch]
format = "[$symbol $branch]($style)"
style = "bg:236 fg:yellow"
symbol = "⎇"

[git_metrics]
disabled = false
format = "([  $added]($added_style))([  $deleted]($deleted_style))"
added_style = "bg:236 fg:green"
deleted_style = "bg:236 fg:red"

[username]
show_always = true
format = "[$user](green)"

[hostname]
ssh_only = false
ssh_symbol = "[ssh:](fg)"
format = "[$ssh_symbol$hostname](green)"

[directory]
style = "dimmed blue"
repo_root_style = "blue"
before_repo_root_style = "blue"
truncate_to_repo = false
truncation_length = 1000
read_only = " "

[time]
format = " [$time]($style)"
style = "0"
disabled = false

[fill]
symbol = '┈'
style = "236"

[cmd_duration]
format = " [ $duration ]($style)[┈┈](236)"
style = "0"
min_time = 1
show_milliseconds = true

# TODO: venv
