#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.desktop_config/xorg/xmonad"

cpp -P -I"$DIR" ~/.Xdefaults.edit > ~/.Xdefaults
if [ -f ~/.desktop_type ]; then
	CONFIG=`cat ~/.desktop_type`
elif [ -f /proc/acpi/battery/BAT0/ ]; then
	CONFIG=laptop
else
	CONFIG=desktop
fi

if [ "$CONFIG" = work ]; then
	cpp -P -I"$DIR" -DCONFIG_WORK    ~/.xmonad/xmonad.hs.in > ~/.xmonad/xmonad.hs
else
	cpp -P -I"$DIR" -DCONFIG_DESKTOP ~/.xmonad/xmonad.hs.in > ~/.xmonad/xmonad.hs
fi

if [ "$CONFIG" = work ]; then
	xrandr --output HDMI1 --rotate left --left-of HDMI2
fi
xrdb ~/.Xresources
xsetroot -cursor_name left_ptr -solid '#000000'
setxkbmap pl
if [ "$CONFIG" != desktop ]; then
	xmodmap ~/.Xmodmap
fi
xset r rate 250 20
# sleeps to make sure the order is correct
(
	~/.xmonad/terminal.sh stats -e bash -c "tail -f /var/log/messages | ccze" &
	sleep 1
	~/.xmonad/terminal.sh stats -e htop &
) &
for i in `seq 1 1 4`; do
	~/.xmonad/terminal.sh tempterm &
done
if [ "$CONFIG" = work ]; then
	gajim &
	thunderbird &
        ~/scripts/stbstatus_updater.sh &
	xautolock -corners '0+00' -locker ~/.slock/slock_wrapper.sh -cornerdelay 2 -cornerredelay 10 -time 3 &
	~/.xmonad/terminal.sh stb -e ~/scripts/run_stb.sh 5444 &
	~/.xmonad/terminal.sh stb -e ~/scripts/run_stb.sh 15444 &
	~/.xmonad/terminal.sh stb -e ~/scripts/run_stb.sh 25444 &
	sleep 0.5
	~/.xmonad/terminal.sh stb &
	~/.xmonad/terminal.sh stb &
else
	echo
fi
xset s off
xset dpms 120 120 120
xset m 7/4 7

(sleep 1 && ~/.xmonad/panels_launch.sh &)
ulimit -s 16000 && exec /usr/bin/xmonad
