#!/bin/bash

cpp ~/.Xdefaults.edit > ~/.Xdefaults
if [[ -a ~/.desktop_type ]]; then
	CONFIG=`cat ~/.desktop_type`
elif [[ -a /proc/acpi/battery/BAT0/ ]]; then
	CONFIG=laptop
else
	CONFIG=desktop
fi
if [[ "$CONFIG" == work ]]; then
	xrandr --output DVI-I-1 --rotate left --left-of VGA-1
fi
xsetroot -cursor_name left_ptr -solid '#000000'
setxkbmap pl
if [[ "$CONFIG" != desktop ]]; then
	xmodmap ~/.Xmodmap
fi
xset r rate 250 20
# sleeps to make sure the order is correct
(
	urxvt -name stats -e bash -c "tail -f /var/log/messages | ccze" &
	sleep 1
	urxvt -name stats -e ncmpcpp &
	sleep 1
	urxvt -name stats -e htop &
) &
if [[ "$CONFIG" == work ]]; then
	gajim &
	thunderbird &
        ~/scripts/stbstatus_updater.sh &
	xautolock -corners '0+00' -locker pyxtrlock -cornerdelay 2 -cornerredelay 10 -time 3 &
else
	gajim &
fi
xset dpms 120 120 120
xset m 7/4 7

(sleep 1 && ~/.xmonad/panels_launch.sh &)
ulimit -s 16000 && exec /usr/bin/xmonad
