# /etc/skel/.bashrc
#
# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !


# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi


# Put your fun stuff here.

function editor()
{
	E=gvim
	[[ -z $DISPLAY ]] && E=vim
	$E $* > /dev/null 2>&1
}

function alert()
{
	[ -n "$*" ] && echo -ne "\033]0;$*\a"
	echo -ne "$*...\a"
	read
}

export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel"
export EDITOR="vim"
alias vi='editor'
alias ls="ls --color=always"
alias grep="grep --colour=always"
alias e="e -F"
for prog in oowriter ooimpress oocalc oobase oodraw audacity eclipse; do
	alias $prog="GTK2_RC_FILES=/usr/share/themes/Default/ $prog"
done

if [ -f /usr/share/mc/mc.gentoo ]; then
	. /usr/share/mc/mc.gentoo
fi

[[ -f /etc/profile.d/bash-completion.sh ]] && source /etc/profile.d/bash-completion.sh
